//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De.DataExperts.conhITApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hallo Welt")]
        public string Text {
            get {
                return ((string)(this["Text"]));
            }
            set {
                this["Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double MenuFontSize {
            get {
                return ((double)(this["MenuFontSize"]));
            }
            set {
                this["MenuFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double MenuRadius {
            get {
                return ((double)(this["MenuRadius"]));
            }
            set {
                this["MenuRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public double HeaderFontSize {
            get {
                return ((double)(this["HeaderFontSize"]));
            }
            set {
                this["HeaderFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Neugierig? Hebe die Hand.")]
        public string BubbleText {
            get {
                return ((string)(this["BubbleText"]));
            }
            set {
                this["BubbleText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double BubbleFontSize {
            get {
                return ((double)(this["BubbleFontSize"]));
            }
            set {
                this["BubbleFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 105, 91")]
        public global::System.Drawing.Color MenuColor1 {
            get {
                return ((global::System.Drawing.Color)(this["MenuColor1"]));
            }
            set {
                this["MenuColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 205, 191")]
        public global::System.Drawing.Color MenuColor2 {
            get {
                return ((global::System.Drawing.Color)(this["MenuColor2"]));
            }
            set {
                this["MenuColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 155, 141")]
        public global::System.Drawing.Color MenuStrokeColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStrokeColor"]));
            }
            set {
                this["MenuStrokeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Seconds2Wait_HelpGrab {
            get {
                return ((int)(this["Seconds2Wait_HelpGrab"]));
            }
            set {
                this["Seconds2Wait_HelpGrab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Seconds2Wait_HelpActivate {
            get {
                return ((int)(this["Seconds2Wait_HelpActivate"]));
            }
            set {
                this["Seconds2Wait_HelpActivate"] = value;
            }
        }
    }
}
