//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.261
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinectServer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinectServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die   �Fh�  �V(&gt;( @�����������������ʦ���������k��H��%������z�b�Js2P���������k��Hs�%W�U�I�=�1�%sP���������kk�HH�%%�����sP���Ǳ�����k�sH�W%�U�I�=�1�%sP�����Ԏ��k��H��%�����z�b�Js2P����������k��H��%���������ssPP����������k��H��%������z�bsJP2����������k��Hs�%W�U� [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string FOLDER {
            get {
                return ResourceManager.GetString("FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Skelet&lt;/title&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;wz_jsgraphics.js&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div id=&quot;skelet&quot; style=&quot;height: 100%; width: 100%&quot;&gt;
        ///    &lt;/div&gt;
        ///    &lt;script type=&quot;text/javascript&quot;&gt;
        ///        function httpGet(theUrl)
        ///        {
        ///            var xmlHttp = null;
        ///            xmlHttp = new XMLHttpRequest();
        ///            xmlHttp.open( &quot;GET&quot;, theUrl, false );
        ///            xmlHttp.send( null );
        ///     [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /* This notice must be untouched at all times.
        ///
        ///wz_jsgraphics.js    v. 2.33
        ///The latest version is available at
        ///http://www.walterzorn.com
        ///or http://www.devira.com
        ///or http://www.walterzorn.de
        ///
        ///Copyright (c) 2002-2004 Walter Zorn. All rights reserved.
        ///Created 3. 11. 2002 by Walter Zorn (Web: http://www.walterzorn.com )
        ///Last modified: 24. 10. 2005
        ///
        ///Performance optimizations for Internet Explorer
        ///by Thomas Frank and John Holdsworth.
        ///fillPolygon method implemented by Matthieu Haller.
        ///
        ///High Perform [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string wz_jsgraphics {
            get {
                return ResourceManager.GetString("wz_jsgraphics", resourceCulture);
            }
        }
    }
}
